django_odi/django_odi/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'', include('odi.urls', namespace='odi'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_odi/odi/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^compress/$', views.upload, name='compress'),
]

django_odi/odi/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .utils import optimize_image


def home(request):
    return render(request, 'index.html')


def upload(request):
    if request.method == 'POST':
        file = request.FILES.get('file')

        image_data = optimize_image(file)

        return JsonResponse({'url': image_data.get('url'), 'original_size': image_data.get('original_size'),
                             'size': image_data.get('size')})

    return render(request, 'index.html')

django_odi/templates/index.html
{% load static %}
<!doctype html>
<html>
<head>
  <title>Django ODI</title>
  <meta charset='utf-8'>
  <link rel='stylesheet' href='{% static "dropzone.min.css" %}'>
  <link rel="stylesheet" href='{% static "main.css" %}'>
</head>

<body>
<h1>Compresor de imágenes</h1>
<form action='{% url "odi:compress" %}' enctype='multipart/form-data' method='post' class='dropzone' id='myDropzone'>
  {% csrf_token %}
  <div class="fallback">
    <input name='file' type='file'/>
  </div>
</form>

<ul id='ul_images'></ul>

<footer>ver repositorio en <a href='https://github.com/alexander-ae/django-odi' target='_blank'>github</a></footer>

<script src='{% static "dropzone.min.js" %}'></script>
<script type="text/javascript">
    var ul_images = document.getElementById('ul_images');

    Dropzone.options.myDropzone = {
        paramName: 'file',
        autoProcessQueue: true,
        parallelUploads: 1,
        acceptedFiles: 'image/jpeg,image/png',
        dictDefaultMessage: 'Arrastre los archivos aquí',

        init: function () {
            this.on('success', function (file, responseText) {
                ul_images.innerHTML += '<li><a href="' + responseText.url + '" target="_blank">' + file.name + '</a> : ' + responseText.original_size + ' / ' + responseText.size + '</li>';
            });
        }
    };
</script>
</body>
</html>